;;; emacs-sherpa-onnx-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;;; Code:



;;; Generated autoloads from emacs-sherpa.el

(autoload 'emacs-sherpa-start-daemon "emacs-sherpa"
"Start the resident ASR daemon (loads the model once; takes a few seconds)." t)
(autoload 'emacs-sherpa-stop-daemon "emacs-sherpa"
"Stop the resident ASR daemon." t)
(autoload 'emacs-sherpa-dictate "emacs-sherpa"
"Toggle recording: start recording the mic, or stop and transcribe." t)
(autoload 'emacs-sherpa-dictate-file "emacs-sherpa"
"Transcribe an existing WAV FILE via the daemon, insert text at point.

(fn FILE)" t)
(autoload 'emacs-sherpa-cancel "emacs-sherpa"
"Cancel an in-progress recording without transcribing." t)
(register-definition-prefixes "emacs-sherpa" '("emacs-sherpa-"))

;;; End of scraped data

(provide 'emacs-sherpa-onnx-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; emacs-sherpa-onnx-autoloads.el ends here
